spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  profiles:
    active: local
    include: secret

  servlet.multipart.max-file-size: 5MB
  servlet.multipart.max-request-size: 5MB


